### ISSUE TITLE
Make pacify/kill options accidents

### ISSUE THREAD

**Issue by bennett-sh** [atampy25/h3-reality-control#2]
I think it would be cool if the pacify/kill options would be accidents so SA is not lost.

**Comment by atampy25** [comment]
I did think about that when designing the mod; I chose not to make them accidents for balance reasons (which is a bit weird given the mod is basically a trainer already but still, I wanted to at least somewhat limit how OP it was)

You can pretty easily make them accidents yourself though by making the various references to the actor proxy/actor death entities use `KillNotHitman` for example

**Comment by bennett-sh** [comment]
I've never gone past repository & QuickEdit mods. Would I add it to the
npcactor.entity.patch.json via QuickEdit?

**Comment by atampy25** [comment]
The entity.json and entity.patch.json are QuickEntity formats; you can use QuickEntity Editor to edit them.

**Comment by bennett-sh** [comment]
Thanks. Do you by chance know how to use this property on the ZActorDeathEntity.class to make the death or pacification look like an accident?

```json
{
    "nPropertyID": "m_AccidentContext",
    "value": {
        "$type": "ZEntityReference",
        "$val": {
            "m_EntityID": {
                 "m_sStr": ""
             },
             "m_sExposedEntity": ""
        }
    }
}
```

**Comment by bennett-sh** [comment]
PR #3
